server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/user/**
          filters:
            - name: JwtFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: ERROR
        security: DEBUG
    reactor.netty.http.client: ERROR
